/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutServicesRouteImport } from './routes/_layout.services'
import { Route as LayoutReferralRouteImport } from './routes/_layout.referral'
import { Route as LayoutProjectsRouteImport } from './routes/_layout.projects'
import { Route as LayoutPricesRouteImport } from './routes/_layout.prices'
import { Route as LayoutFaqRouteImport } from './routes/_layout.faq'
import { Route as LayoutContactsRouteImport } from './routes/_layout.contacts'
import { Route as LayoutCatalogRouteImport } from './routes/_layout.catalog'
import { Route as LayoutCalculatorRouteImport } from './routes/_layout.calculator'
import { Route as LayoutBlogRouteImport } from './routes/_layout.blog'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as LayoutServicesHomeRouteImport } from './routes/_layout.services_.home'
import { Route as LayoutServicesBusinessRouteImport } from './routes/_layout.services_.business'
import { Route as LayoutProjectsHomeRouteImport } from './routes/_layout.projects.home'
import { Route as LayoutProjectsBusinessRouteImport } from './routes/_layout.projects.business'
import { Route as LayoutProjectsSlugRouteImport } from './routes/_layout.projects.$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesRoute = LayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReferralRoute = LayoutReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPricesRoute = LayoutPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFaqRoute = LayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsRoute = LayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogRoute = LayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalculatorRoute = LayoutCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesHomeRoute = LayoutServicesHomeRouteImport.update({
  id: '/services_/home',
  path: '/services/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesBusinessRoute = LayoutServicesBusinessRouteImport.update({
  id: '/services_/business',
  path: '/services/business',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsHomeRoute = LayoutProjectsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsBusinessRoute = LayoutProjectsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsSlugRoute = LayoutProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/blog': typeof LayoutBlogRoute
  '/calculator': typeof LayoutCalculatorRoute
  '/catalog': typeof LayoutCatalogRoute
  '/contacts': typeof LayoutContactsRoute
  '/faq': typeof LayoutFaqRoute
  '/prices': typeof LayoutPricesRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/referral': typeof LayoutReferralRoute
  '/services': typeof LayoutServicesRoute
  '/projects/$slug': typeof LayoutProjectsSlugRoute
  '/projects/business': typeof LayoutProjectsBusinessRoute
  '/projects/home': typeof LayoutProjectsHomeRoute
  '/services/business': typeof LayoutServicesBusinessRoute
  '/services/home': typeof LayoutServicesHomeRoute
}
export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/blog': typeof LayoutBlogRoute
  '/calculator': typeof LayoutCalculatorRoute
  '/catalog': typeof LayoutCatalogRoute
  '/contacts': typeof LayoutContactsRoute
  '/faq': typeof LayoutFaqRoute
  '/prices': typeof LayoutPricesRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/referral': typeof LayoutReferralRoute
  '/services': typeof LayoutServicesRoute
  '/': typeof LayoutIndexRoute
  '/projects/$slug': typeof LayoutProjectsSlugRoute
  '/projects/business': typeof LayoutProjectsBusinessRoute
  '/projects/home': typeof LayoutProjectsHomeRoute
  '/services/business': typeof LayoutServicesBusinessRoute
  '/services/home': typeof LayoutServicesHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/blog': typeof LayoutBlogRoute
  '/_layout/calculator': typeof LayoutCalculatorRoute
  '/_layout/catalog': typeof LayoutCatalogRoute
  '/_layout/contacts': typeof LayoutContactsRoute
  '/_layout/faq': typeof LayoutFaqRoute
  '/_layout/prices': typeof LayoutPricesRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/referral': typeof LayoutReferralRoute
  '/_layout/services': typeof LayoutServicesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$slug': typeof LayoutProjectsSlugRoute
  '/_layout/projects/business': typeof LayoutProjectsBusinessRoute
  '/_layout/projects/home': typeof LayoutProjectsHomeRoute
  '/_layout/services_/business': typeof LayoutServicesBusinessRoute
  '/_layout/services_/home': typeof LayoutServicesHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/calculator'
    | '/catalog'
    | '/contacts'
    | '/faq'
    | '/prices'
    | '/projects'
    | '/referral'
    | '/services'
    | '/projects/$slug'
    | '/projects/business'
    | '/projects/home'
    | '/services/business'
    | '/services/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/calculator'
    | '/catalog'
    | '/contacts'
    | '/faq'
    | '/prices'
    | '/projects'
    | '/referral'
    | '/services'
    | '/'
    | '/projects/$slug'
    | '/projects/business'
    | '/projects/home'
    | '/services/business'
    | '/services/home'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/blog'
    | '/_layout/calculator'
    | '/_layout/catalog'
    | '/_layout/contacts'
    | '/_layout/faq'
    | '/_layout/prices'
    | '/_layout/projects'
    | '/_layout/referral'
    | '/_layout/services'
    | '/_layout/'
    | '/_layout/projects/$slug'
    | '/_layout/projects/business'
    | '/_layout/projects/home'
    | '/_layout/services_/business'
    | '/_layout/services_/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services': {
      id: '/_layout/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LayoutServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/referral': {
      id: '/_layout/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof LayoutReferralRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prices': {
      id: '/_layout/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof LayoutPricesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/faq': {
      id: '/_layout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LayoutFaqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts': {
      id: '/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog': {
      id: '/_layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calculator': {
      id: '/_layout/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof LayoutCalculatorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services_/home': {
      id: '/_layout/services_/home'
      path: '/services/home'
      fullPath: '/services/home'
      preLoaderRoute: typeof LayoutServicesHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services_/business': {
      id: '/_layout/services_/business'
      path: '/services/business'
      fullPath: '/services/business'
      preLoaderRoute: typeof LayoutServicesBusinessRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/home': {
      id: '/_layout/projects/home'
      path: '/home'
      fullPath: '/projects/home'
      preLoaderRoute: typeof LayoutProjectsHomeRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/business': {
      id: '/_layout/projects/business'
      path: '/business'
      fullPath: '/projects/business'
      preLoaderRoute: typeof LayoutProjectsBusinessRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$slug': {
      id: '/_layout/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof LayoutProjectsSlugRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
  }
}

interface LayoutProjectsRouteChildren {
  LayoutProjectsSlugRoute: typeof LayoutProjectsSlugRoute
  LayoutProjectsBusinessRoute: typeof LayoutProjectsBusinessRoute
  LayoutProjectsHomeRoute: typeof LayoutProjectsHomeRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsSlugRoute: LayoutProjectsSlugRoute,
  LayoutProjectsBusinessRoute: LayoutProjectsBusinessRoute,
  LayoutProjectsHomeRoute: LayoutProjectsHomeRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutBlogRoute: typeof LayoutBlogRoute
  LayoutCalculatorRoute: typeof LayoutCalculatorRoute
  LayoutCatalogRoute: typeof LayoutCatalogRoute
  LayoutContactsRoute: typeof LayoutContactsRoute
  LayoutFaqRoute: typeof LayoutFaqRoute
  LayoutPricesRoute: typeof LayoutPricesRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutReferralRoute: typeof LayoutReferralRoute
  LayoutServicesRoute: typeof LayoutServicesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutServicesBusinessRoute: typeof LayoutServicesBusinessRoute
  LayoutServicesHomeRoute: typeof LayoutServicesHomeRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutBlogRoute: LayoutBlogRoute,
  LayoutCalculatorRoute: LayoutCalculatorRoute,
  LayoutCatalogRoute: LayoutCatalogRoute,
  LayoutContactsRoute: LayoutContactsRoute,
  LayoutFaqRoute: LayoutFaqRoute,
  LayoutPricesRoute: LayoutPricesRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutReferralRoute: LayoutReferralRoute,
  LayoutServicesRoute: LayoutServicesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutServicesBusinessRoute: LayoutServicesBusinessRoute,
  LayoutServicesHomeRoute: LayoutServicesHomeRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
